# Generated by Django 3.2.6 on 2021-08-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0002_auto_20210825_1548'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscription',
            name='duration',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
