# Generated by Django 3.2.6 on 2021-08-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0005_auto_20210828_1437'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subactive',
            name='end_date',
            field=models.DateTimeField(),
        ),
    ]
