# Generated by Django 3.2.6 on 2021-08-28 15:05

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_alter_subactive_end_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subactive',
            name='end_date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
