# Generated by Django 3.2.6 on 2021-08-28 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0008_alter_subactive_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subactive',
            name='description',
            field=models.CharField(default='', max_length=80),
        ),
    ]
