# Generated by Django 3.2.6 on 2021-08-31 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0009_alter_subactive_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subactive',
            options={'ordering': ('-date',)},
        ),
    ]
